# Generated by Django 5.1.7 on 2026-05-05 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_paciente_importacion_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_ultima_inasistencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_ultima_inasistencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='n_inasistencias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_cambio_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InasistenciaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('motivo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='pacientes.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LlamadoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('telefono_usado', models.CharField(blank=True, default='', max_length=30)),
                ('resultado', models.CharField(choices=[('CONTESTA_CONFIRMADO', 'Contesta y confirma'), ('NO_CONTESTA', 'No contesta'), ('NUMERO_EQUIVOCADO', 'Numero equivocado'), ('REAGENDAR_LLAMADO', 'Reagendar llamado'), ('RECHAZA_ATENCION', 'Rechaza atencion'), ('YA_RESUELTO', 'Ya resuelto'), ('OTRO', 'Otro')], max_length=30)),
                ('notas', models.TextField(blank=True, default='')),
                ('proxima_accion', models.CharField(blank=True, default='', max_length=160)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamados', to='pacientes.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
