# Generated by Django 5.1.7 on 2026-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_registroagendapaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sector_cesfam',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sector_oficial',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['sector_cesfam'], name='paciente_sector_cesfam_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['sector_oficial'], name='paciente_sector_oficial_idx'),
        ),
    ]
