# Generated by Django 5.1.7 on 2026-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_paciente_sector_cesfam_paciente_sector_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='asignado_historico',
            field=models.BooleanField(default=False),
        ),
    ]
