# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importar", "0003_alter_importacionmensual_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacionmensual",
            name="observaciones_revision",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
